//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANULACION_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANULACION_VENTA()
        {
            this.DETALLE_ANULACION_VENTA = new HashSet<DETALLE_ANULACION_VENTA>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public Nullable<System.DateTime> FECHA_ANULACION { get; set; }
        public string MOTIVO { get; set; }
        public int CLIENTE_ID { get; set; }
        public int EMPLEADO_ID { get; set; }
        public int VENTAS_ID { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ANULACION_VENTA> DETALLE_ANULACION_VENTA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
