//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_RECEPCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTROL_RECEPCION()
        {
            this.DETALLE_CONTROL_RECEPCION = new HashSet<DETALLE_CONTROL_RECEPCION>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<System.DateTime> FECHA_APROVACION { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public int EMPLEADO_ID { get; set; }
        public int ESTADO_CONTROL_RECEPCION_ID { get; set; }
        public int ORDEN_PEDIDO_ID { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONTROL_RECEPCION> DETALLE_CONTROL_RECEPCION { get; set; }
        public virtual ESTADO_CONTROL_RECEPCION ESTADO_CONTROL_RECEPCION { get; set; }
        public virtual ORDEN_PEDIDO ORDEN_PEDIDO { get; set; }
    }
}
