//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN_PEDIDO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> MONTO_TOTAL { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public int MULTI_MONEDA_ID { get; set; }
        public int ORDEN_PEDIDO_ID { get; set; }
        public int PRODUCTO_ID { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual MULTI_MONEDA MULTI_MONEDA { get; set; }
        public virtual ORDEN_PEDIDO ORDEN_PEDIDO { get; set; }
    }
}
