//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONTROL_RECEPCION
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public Nullable<int> CANTIDAD_INGRESADA { get; set; }
        public Nullable<int> CANTIDAD_TOTAL { get; set; }
        public string COMENTARIO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public int CONTROL_RECEPCION_ID { get; set; }
        public int ESTADO_RECEPCION_ID { get; set; }
        public int MULTI_MONEDA_ID { get; set; }
        public int PRODUCTO_ID { get; set; }
    
        public virtual CONTROL_RECEPCION CONTROL_RECEPCION { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ESTADO_RECEPCION ESTADO_RECEPCION { get; set; }
        public virtual MULTI_MONEDA MULTI_MONEDA { get; set; }
    }
}
