//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public int RESERVA_HORA_ID { get; set; }
        public int SUCURSAL_ID { get; set; }
        public Nullable<decimal> VALOR_FINAL { get; set; }
        public string ESTADO_DIAGNOSTICO { get; set; }
    
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual RESERVA_HORA RESERVA_HORA { get; set; }
    }
}
