//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesServiexpress : DbContext
    {
        public EntitiesServiexpress()
            : base("name=EntitiesServiexpress")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANULACION_VENTA> ANULACION_VENTA { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMUNA> COMUNA { get; set; }
        public virtual DbSet<CONTROL_RECEPCION> CONTROL_RECEPCION { get; set; }
        public virtual DbSet<DETALLE_ANULACION_VENTA> DETALLE_ANULACION_VENTA { get; set; }
        public virtual DbSet<DETALLE_CONTROL_RECEPCION> DETALLE_CONTROL_RECEPCION { get; set; }
        public virtual DbSet<DETALLE_ORDEN_PEDIDO> DETALLE_ORDEN_PEDIDO { get; set; }
        public virtual DbSet<DETALLE_VENTAS> DETALLE_VENTAS { get; set; }
        public virtual DbSet<DIAGNOSTICO> DIAGNOSTICO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<ESTADO_CLIENTE> ESTADO_CLIENTE { get; set; }
        public virtual DbSet<ESTADO_CONTROL_RECEPCION> ESTADO_CONTROL_RECEPCION { get; set; }
        public virtual DbSet<ESTADO_EMPLEADO> ESTADO_EMPLEADO { get; set; }
        public virtual DbSet<ESTADO_EMPRESA> ESTADO_EMPRESA { get; set; }
        public virtual DbSet<ESTADO_ORDEN_PEDIDO> ESTADO_ORDEN_PEDIDO { get; set; }
        public virtual DbSet<ESTADO_PERSONA> ESTADO_PERSONA { get; set; }
        public virtual DbSet<ESTADO_PRODUCTO> ESTADO_PRODUCTO { get; set; }
        public virtual DbSet<ESTADO_PROVEEDOR> ESTADO_PROVEEDOR { get; set; }
        public virtual DbSet<ESTADO_RECEPCION> ESTADO_RECEPCION { get; set; }
        public virtual DbSet<ESTADO_RESERVA> ESTADO_RESERVA { get; set; }
        public virtual DbSet<ESTADO_SERVICIO> ESTADO_SERVICIO { get; set; }
        public virtual DbSet<ESTADO_SUCURSAL> ESTADO_SUCURSAL { get; set; }
        public virtual DbSet<ESTADO_USUARIO> ESTADO_USUARIO { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MARCA_VEHICULO> MARCA_VEHICULO { get; set; }
        public virtual DbSet<MULTI_EMPRESA> MULTI_EMPRESA { get; set; }
        public virtual DbSet<MULTI_MONEDA> MULTI_MONEDA { get; set; }
        public virtual DbSet<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<RESERVA_HORA> RESERVA_HORA { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<TIPO_EMPLEADO> TIPO_EMPLEADO { get; set; }
        public virtual DbSet<TIPO_ORDEN_PEDIDO> TIPO_ORDEN_PEDIDO { get; set; }
        public virtual DbSet<TIPO_PERSONA> TIPO_PERSONA { get; set; }
        public virtual DbSet<TIPO_PROVEEDOR> TIPO_PROVEEDOR { get; set; }
        public virtual DbSet<TIPO_RESERVA> TIPO_RESERVA { get; set; }
        public virtual DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<TIPO_VEHICULO> TIPO_VEHICULO { get; set; }
        public virtual DbSet<TIPO_VENTA> TIPO_VENTA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VEHICULO> VEHICULO { get; set; }
        public virtual DbSet<VENTAS> VENTAS { get; set; }
        public virtual DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public virtual DbSet<ESTADO_SERVICIO_X_DIAGNOSTICO> ESTADO_SERVICIO_X_DIAGNOSTICO { get; set; }
        public virtual DbSet<PRODUCTOS_X_DIAGNOSTICO> PRODUCTOS_X_DIAGNOSTICO { get; set; }
        public virtual DbSet<SERVICIOS_X_DIAGNOSTICO> SERVICIOS_X_DIAGNOSTICO { get; set; }
    }
}
