//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_PEDIDO()
        {
            this.CONTROL_RECEPCION = new HashSet<CONTROL_RECEPCION>();
            this.DETALLE_ORDEN_PEDIDO = new HashSet<DETALLE_ORDEN_PEDIDO>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public Nullable<decimal> CANTIDAD_TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public Nullable<decimal> MONTO_TOTAL { get; set; }
        public int EMPLEADO_ID { get; set; }
        public int ESTADO_ORDEN_PEDIDO_ID { get; set; }
        public int MULTI_MONEDA_ID { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public int SUCURSAL_ID { get; set; }
        public int TIPO_ORDEN_PEDIDO_ID { get; set; }
        public string EMAIL_PROVEEDOR { get; set; }
        public string EMAIL_SUCURSAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_RECEPCION> CONTROL_RECEPCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN_PEDIDO> DETALLE_ORDEN_PEDIDO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO_ORDEN_PEDIDO ESTADO_ORDEN_PEDIDO { get; set; }
        public virtual MULTI_MONEDA MULTI_MONEDA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TIPO_ORDEN_PEDIDO TIPO_ORDEN_PEDIDO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
