//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS_X_DIAGNOSTICO
    {
        public decimal ID_PXD { get; set; }
        public decimal ID_DIAGNOSTICO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD_PROD { get; set; }
    }
}
