//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA_HORA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA_HORA()
        {
            this.DIAGNOSTICO = new HashSet<DIAGNOSTICO>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public int CLIENTE_ID { get; set; }
        public int EMPLEADO_ID { get; set; }
        public int ESTADO_RESERVA_ID { get; set; }
        public int SUCURSAL_ID { get; set; }
        public int TIPO_RESERVA_ID { get; set; }
        public int VEHICULO_ID { get; set; }
        public string ORSERVACION_FINAL { get; set; }
        public Nullable<System.DateTime> FECHA_RESERVA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIAGNOSTICO> DIAGNOSTICO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO_RESERVA ESTADO_RESERVA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        public virtual TIPO_RESERVA TIPO_RESERVA { get; set; }
    }
}
