//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public string CONTRACENA { get; set; }
        public string NOMBRE { get; set; }
        public int ESTADO_USUARIO_ID { get; set; }
        public int PERSONA_ID { get; set; }
        public int SUCURSAL_ID { get; set; }
        public int TIPO_USUARIO_ID { get; set; }
    
        public virtual ESTADO_USUARIO ESTADO_USUARIO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
