//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCServiexpress.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTAS()
        {
            this.ANULACION_VENTA = new HashSet<ANULACION_VENTA>();
            this.DETALLE_VENTAS = new HashSet<DETALLE_VENTAS>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMO_UPDATE { get; set; }
        public Nullable<int> CANTIDAD_TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA_VENTA { get; set; }
        public Nullable<decimal> MONTO_TOTAL { get; set; }
        public int CLIENTE_ID { get; set; }
        public int EMPLEADO_ID { get; set; }
        public int MULTI_MONEDA_ID { get; set; }
        public int SUCURSAL_ID { get; set; }
        public int TIPO_VENTA_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANULACION_VENTA> ANULACION_VENTA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTAS> DETALLE_VENTAS { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual MULTI_MONEDA MULTI_MONEDA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TIPO_VENTA TIPO_VENTA { get; set; }
    }
}
